
{% set name = "clinker" %}
{% set version = "1.32" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Oshlack/Clinker/archive/v{{ version }}.tar.gz
  sha256: "5dbb97da27f29f53a8282e456ba0093bbdde292eb9e76405434117da4d1a76be"

build:
  number: 1
  noarch: generic

requirements:
  run:
    - bpipe
    - samtools
    - star ==2.5.3a
    - bioconductor-biomart ==2.34.2
    - bioconductor-gviz ==1.22.3
    - python >=2.7,<3

test:
  commands:
    - cd /tmp &&  bpipe --help
    - cd /tmp &&  clinker -h

about:
  home: https://github.com/Oshlack/Clinker
  summary: |
    Clinker is a bioinformatics pipeline that generates a superTranscript
    from popular fusion finder outputs (JAFFA, tophatFusion, SOAP, deFUSE,
    Pizzly, etc), that can be then be either viewed in genome viewers such
    as IGV or through the included plotting feature developed with GViz.
  license: MIT
  
extra:
  notes: |
    Wrapper script provided to indicate clinker is a bpipe pipeline,
    provide example command from wiki, and also a passthrough option.
    Tests run from /tmp to avoid Docker permission error.
  container:
    extended-base: True
